<div>
    <h1>Liste de vos commandes</h1>
    <form action="index.php?route=orders" method="POST">
        
     <label for="past-order">Vos commandes</label>
    
          <select class="" name="past-orders" id="">
                  <option value=""></option>
                  <option value=""></option>
                  <option value=""></option>
                  <option value=""></option>
         
     </select>
        
        
        
    </form>
    
    
</div>