<h1>Créer un compte</h1>
<form action="index.php?route=user-register" method="POST">
    
    <input type="hidden" name="formName" value="user-register"/>

    <label for="username">Nom d'utilisateur</label>
    <input type="text" id="username" name="username">
    
    <label for="email">Email</label>
    <input type="email" id="email" name="email">

    <label for="password">Mot de passe</label>
    <input type="password" id="password" name="password">
   
    <label for="confirm-password">Confirmer votre Mot de passe</label>
    <input type="password" id="confirm-password" name="confirm-password">

    <input type="submit" value="Créer votre compte">
</form>