<form method="POST" action="index.php?route="> <!--vers où ?? pierre à fait la liste des produits-->
    <input type="hidden" name="formName" value="getProductsByCategory"/>
    <label for="category_list">Quelle catégorie ?</label>
    <select name="category_list">
        <?php
            $categories = $data;
            foreach($categories as $categorie)
            {
                ?>
                <option value="<?= $categorie['id']; ?>"> <?= $categorie['name']; ?> </option>
                <?php
            }
        ?>
    </select>
    <input type="submit" value="Submit"/>
</form>